# Global Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Rule files
rule_files:
  - "rules/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

# Scrape configurations
scrape_configs:
  # API Service
  - job_name: "api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]
    scrape_interval: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "http_.*"
        action: keep

  # Web Service
  - job_name: "web"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["web:5000"]
    scrape_interval: 10s

  # Dashboard Service
  - job_name: "dashboard"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["dashboard:8501"]
    scrape_interval: 10s

  # Worker Service
  - job_name: "worker"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["worker:8000"]
    scrape_interval: 10s

  # Redis
  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]
    scrape_interval: 10s

  # PostgreSQL
  - job_name: "postgresql"
    static_configs:
      - targets: ["postgresql-exporter:9187"]
    scrape_interval: 10s

  # Node Exporter (System Metrics)
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 10s

  # Windows Exporter (Windows Metrics)
  - job_name: "windows"
    static_configs:
      - targets: ["localhost:9182"]
    scrape_interval: 10s